# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: <SecretProviderClassName> #replace with your secret provider class name. Must be all lower case
spec:
  provider: azure
  secretObjects:
    - secretName: <SecretObjectName> #Must be all lower case
      type: Opaque
      data:
        - objectName: <SecretNameInKeyVault>
          key: <SecretKey>
        

  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true' # Set to true for using managed identity
    userAssignedIdentityID: '<ClienIdOfUserManagedIdentity>' # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: <KeyVaultName> #replace with your key vault name
    cloudName: 'AzurePublicCloud' # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: <SecretNameInKeyVault>
          objectType: secret        
        

    tenantId: <TenantId>
