version: "3.8"

services:
  sample-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
